version: '1.0.3'
services:
  php_today:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
  mysql_app:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "8082:80"
    environment:
      - MYSQL_DATABASE=school_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql_app
      - PMA_PORT=3306
    ports:
      - 9000:80